'use client';

import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import BarcodeForm from './components/BarcodeForm';
import BarcodePreview from './components/BarcodePreview';
import BarcodeTypes from './components/BarcodeTypes';
import BarcodeOptions from './components/BarcodeOptions';
import { BarcodeType } from '../lib/barcode/constants';
import { BarcodeOptions as BarcodeOptionType } from '../lib/barcode/generators';

export default function BarcodeGenerator() {
  const [selectedType, setSelectedType] = useState<BarcodeType>('upc-a');
  const [barcodeData, setBarcodeData] = useState<string>('');
  const [barcodeOptions, setBarcodeOptions] = useState<BarcodeOptionType>({
    scale: 3,
    height: 10,
    includeText: true,
    textAlign: 'center',
    background: '#FFFFFF',
    lineColor: '#000000',
  });

  // Add JSON-LD structured data for SEO
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": "Free Barcode Generator",
    "url": "https://nutrition-label-maker.vercel.app/barcode-generator",
    "applicationCategory": "BusinessApplication",
    "operatingSystem": "Web",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    },
    "description": "Generate professional barcodes for any product or purpose. Create UPC-A, EAN-13, GS1-128, ITF-14, Data Matrix, QR codes and more for retail, logistics, and consumer engagement.",
    "featureList": [
      "UPC-A barcode generation",
      "EAN-13 barcode generation",
      "GS1-128 barcode generation",
      "ITF-14 barcode generation",
      "Data Matrix barcode generation",
      "QR code generation",
      "GS1 DataBar generation",
      "UPC-E barcode generation",
      "EAN-8 barcode generation"
    ],
    "keywords": "barcode generator, UPC barcode generator, EAN-13 barcode maker, GS1-128 barcode creator, QR code generator, product barcodes"
  };

  // Add FAQ schema for SEO
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "Which barcode type should I use for my product?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "For retail products sold in the United States, UPC-A is the most commonly used barcode type. If you plan to sell internationally, consider using EAN-13 instead. For logistics and shipping, GS1-128 or ITF-14 are recommended. For consumer engagement and providing additional product information, QR codes or Data Matrix codes are ideal."
        }
      },
      {
        "@type": "Question",
        "name": "Are the barcodes generated by this tool compliant with industry standards?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes, all barcodes generated by our tool comply with international standards and GS1 specifications. They can be used on product packaging, labels, shipping containers, and for inventory management systems."
        }
      },
      {
        "@type": "Question",
        "name": "How do I download my generated barcode?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "After generating your barcode, you can download it in SVG or PNG format by clicking the respective buttons in the Barcode Preview section. SVG is recommended for print materials as it maintains quality at any size, while PNG is better for digital use."
        }
      }
    ]
  };

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Add structured data for SEO */}
      <script 
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <script 
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      
      <div className="text-center mb-8">
        <h1 className="text-4xl font-bold mb-3">Free Barcode Generator</h1>
        <p className="text-xl text-gray-600 mb-4">
          Create professional barcodes for any product or purpose
        </p>
        <p className="max-w-3xl mx-auto text-gray-600">
          Generate high-quality, industry-standard barcodes for all your needs. 
          Choose from multiple formats including UPC-A, EAN-13, GS1-128, ITF-14, Data Matrix, QR codes, and more. 
          All barcodes comply with GS1 and international standards for retail, logistics, and inventory management.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-1">
          <Card className="p-6">
            <Tabs defaultValue="type" className="w-full">
              <TabsList className="grid w-full grid-cols-2">
                <TabsTrigger value="type">Barcode Type</TabsTrigger>
                <TabsTrigger value="options">Options</TabsTrigger>
              </TabsList>
              <TabsContent value="type">
                <BarcodeTypes 
                  selectedType={selectedType} 
                  onSelectType={setSelectedType} 
                />
              </TabsContent>
              <TabsContent value="options">
                <div className="space-y-4">
                  <h3 className="text-lg font-medium">Customize Barcode</h3>
                  <BarcodeOptions 
                    barcodeType={selectedType}
                    options={barcodeOptions}
                    onOptionsChange={(options) => setBarcodeOptions(prev => ({ ...prev, ...options }))}
                  />
                </div>
              </TabsContent>
            </Tabs>
          </Card>
        </div>

        <div className="lg:col-span-2">
          <Card className="p-6 mb-6">
            <h2 className="text-xl font-semibold mb-4">
              Enter Barcode Data
            </h2>
            <BarcodeForm 
              barcodeType={selectedType}
              onDataChange={setBarcodeData}
              onOptionsChange={(options) => setBarcodeOptions(prev => ({ ...prev, ...options }))}
            />
          </Card>

          <Card className="p-6">
            <h2 className="text-xl font-semibold mb-4">
              Barcode Preview
            </h2>
            <BarcodePreview 
              barcodeType={selectedType}
              barcodeData={barcodeData}
              options={barcodeOptions}
            />
          </Card>
        </div>
      </div>

      <div className="mt-12 space-y-8">
        <Card className="p-6">
          <h2 className="text-2xl font-semibold mb-4">
            Which Barcode Type Should I Use?
          </h2>
          <div className="prose max-w-none">
            <p>
              Choosing the right barcode type is essential for compliance with industry standards and regulations:
            </p>
            <h3 className="text-xl font-medium mt-4">Retail Barcodes</h3>
            <ul>
              <li>
                <strong>UPC-A:</strong> The standard retail barcode in the United States. Used for products sold at retail points of sale. Required for most grocery, retail, and consumer products in the US.
              </li>
              <li>
                <strong>EAN-13:</strong> The international standard for retail products. Required for products sold globally, especially in Europe, Asia, and Australia.
              </li>
              <li>
                <strong>UPC-E:</strong> Condensed version of UPC-A for small packages where space is limited, such as cosmetics, small electronics, or single-serving products.
              </li>
              <li>
                <strong>EAN-8:</strong> Condensed version of EAN-13 for small packages, commonly used for small items internationally.
              </li>
            </ul>
            
            <h3 className="text-xl font-medium mt-4">Logistics & Shipping Barcodes</h3>
            <ul>
              <li>
                <strong>GS1-128:</strong> Advanced barcode for logistics that can encode additional data like batch numbers, expiration dates, and weights. Ideal for shipping containers, warehouse management, and supply chain tracking.
              </li>
              <li>
                <strong>ITF-14:</strong> Used for shipping cartons and cases in the supply chain. Often printed directly on corrugated cardboard packaging for distribution and inventory management.
              </li>
              <li>
                <strong>GS1 DataBar:</strong> Used for variable weight products and coupons. Can encode weight, price, and promotional information directly in the barcode.
              </li>
            </ul>
            
            <h3 className="text-xl font-medium mt-4">Consumer Engagement Barcodes</h3>
            <ul>
              <li>
                <strong>QR Code:</strong> Used for consumer engagement, linking to websites, nutritional information, recipes, or providing allergen information. Increasingly popular for food transparency initiatives.
              </li>
              <li>
                <strong>Data Matrix:</strong> Compact 2D code ideal for small packaging with limited space. Can store more information than traditional barcodes while taking up less space.
              </li>
            </ul>
            
            <p className="mt-4">
              For retail products in the United States, UPC-A is the most commonly used barcode type. 
              If you plan to sell internationally, consider using EAN-13 instead. For shipping, logistics, and inventory management, GS1-128 or ITF-14 are recommended. For marketing and consumer engagement, QR codes are the most versatile option.
            </p>
          </div>
        </Card>
        
        <Card className="p-6">
          <h2 className="text-2xl font-semibold mb-4">
            Barcode Compliance and Standards
          </h2>
          <div className="prose max-w-none">
            <p>
              Product barcodes must comply with specific regulations and standards:
            </p>
            <ul>
              <li>
                <strong>GS1 Standards:</strong> Most retail barcodes must comply with GS1 standards, which govern the format and structure of barcodes used in global commerce.
              </li>
              <li>
                <strong>Industry Regulations:</strong> Different industries have specific requirements for product identification, including retail, healthcare, manufacturing, and logistics.
              </li>
              <li>
                <strong>Placement Guidelines:</strong> Barcodes should be placed in standardized locations on packaging to ensure consistent scanning at point of sale or in warehouse environments.
              </li>
              <li>
                <strong>Scan Quality:</strong> Barcodes must meet minimum scan quality requirements to ensure they can be read by standard scanning equipment in retail and logistics environments.
              </li>
            </ul>
            <p>
              Our barcode generator creates barcodes that meet these requirements, ensuring your products comply with industry standards and regulations across various sectors.
            </p>
          </div>
        </Card>
        
        <Card className="p-6">
          <h2 className="text-2xl font-semibold mb-4">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            <div>
              <h3 className="text-lg font-medium">Do I need to purchase a barcode for my product?</h3>
              <p className="text-gray-700">
                Yes, for retail products you typically need to purchase a legitimate UPC or EAN barcode from GS1, the official global barcode authority. Our generator creates the correct format, but for retail products, you should use your officially assigned GS1 company prefix and product numbers.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium">What information can be encoded in a GS1-128 barcode?</h3>
              <p className="text-gray-700">
                GS1-128 barcodes can encode various data using Application Identifiers (AIs), including product identification (GTIN), batch/lot numbers, production dates, expiration dates, weights, and dimensions. This makes them ideal for food traceability and logistics.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium">How do I ensure my barcode will scan properly?</h3>
              <p className="text-gray-700">
                To ensure proper scanning: maintain adequate quiet zones around the barcode, print at sufficient size and resolution (at least 300 DPI), ensure good contrast between bars and background, and verify the barcode with a scanner before mass production.
              </p>
            </div>
            <div>
              <h3 className="text-lg font-medium">Can I use the same barcode for different product variations?</h3>
              <p className="text-gray-700">
                No, each distinct product variation (different size, flavor, etc.) should have its own unique barcode. Using the same barcode for different products will cause inventory and checkout issues in retail environments.
              </p>
            </div>
          </div>
        </Card>
      </div>
      
      <footer className="mt-12 text-center text-gray-600 text-sm">
        <p>© {new Date().getFullYear()} Nutrition Label Maker | All barcodes generated comply with GS1 standards</p>
        <p className="mt-2">This tool is provided for educational and informational purposes. For retail products, obtain official barcodes from GS1.</p>
      </footer>
    </div>
  );
}
